SELECT * FROM ECOMMERCE_SALES

--CUSTOMER PURCHASE SUMMARY--
SELECT CUSTOMER_ID, CUSTOMER_NAME,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	SUM(QUANTITY) TOTAL_UNITS,
	ROUND(SUM(SALES), 2) TOTAL_REVENUE,
	ROUND(SUM(PROFIT), 2) TOTAL_PROFIT,
	ROUND(SUM(SALES) / COUNT(DISTINCT ORDER_ID), 2) AVERAGE_ORDER_VALUE
FROM ECOMMERCE_SALES
GROUP BY CUSTOMER_ID, CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

--TOP 10 CUST BY REVENUE--
SELECT CUSTOMER_ID, CUSTOMER_NAME,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	SUM(QUANTITY) TOTAL_UNITS,
	ROUND(SUM(SALES), 2) TOTAL_REVENUE,
	ROUND(SUM(PROFIT), 2) TOTAL_PROFIT,
	ROUND(SUM(SALES) / COUNT(DISTINCT ORDER_ID), 2) AVERAGE_ORDER_VALUE
FROM ECOMMERCE_SALES
GROUP BY CUSTOMER_ID, CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--TOP 10 CUST BY PROFIT--
SELECT CUSTOMER_ID, CUSTOMER_NAME,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	SUM(QUANTITY) TOTAL_UNITS,
	ROUND(SUM(SALES), 2) TOTAL_REVENUE,
	ROUND(SUM(PROFIT), 2) TOTAL_PROFIT,
	ROUND(SUM(SALES) / COUNT(DISTINCT ORDER_ID), 2) AVERAGE_ORDER_VALUE
FROM ECOMMERCE_SALES
GROUP BY CUSTOMER_ID, CUSTOMER_NAME
ORDER BY TOTAL_PROFIT DESC
LIMIT 10;

--ONE TIME VS REPEAT CUSTOMERS--
WITH CUSTOMER_ORDERS AS (
	SELECT CUSTOMER_ID,
		COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
	FROM ECOMMERCE_SALES
	GROUP BY CUSTOMER_ID
)
SELECT CASE
	WHEN TOTAL_ORDERS = 1 THEN 'ONE-TIME CSUTOMER'
	ELSE 'REPEAT CUSTOMER'
	END AS CUSTOMER_TYPE,
	COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER_ORDERS
GROUP BY CASE
	WHEN TOTAL_ORDERS = 1 THEN 'ONE-TIME CSUTOMER'
	ELSE 'REPEAT CUSTOMER'
	END
ORDER BY CUSTOMER_COUNT DESC;

-- CUSTOMER ORDER FREQUENCY --
SELECT
    TOTAL_ORDERS,
    COUNT(*) AS NUMBER_OF_CUSTOMERS
FROM
(
    SELECT
        CUSTOMER_ID,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
    FROM ECOMMERCE_SALES
    GROUP BY CUSTOMER_ID
) AS CUSTOMER_DATA
GROUP BY TOTAL_ORDERS
ORDER BY TOTAL_ORDERS;

-- TOP CUSTOMERS BY PROFIT MARGIN --
SELECT
    CUSTOMER_ID, CUSTOMER_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT) / NULLIF(SUM(SALES), 0)) * 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CUSTOMER_ID, CUSTOMER_NAME
HAVING SUM(SALES) > 0
ORDER BY PROFIT_MARGIN DESC
LIMIT 10;


-- HIGH VALUE CUSTOMERS --
SELECT
    CUSTOMER_ID, CUSTOMER_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ECOMMERCE_SALES
GROUP BY CUSTOMER_ID, CUSTOMER_NAME
HAVING SUM(SALES) >= 100000
   AND SUM(PROFIT) > 10000
ORDER BY TOTAL_PROFIT DESC;
