-- PRODUCT PERFORMANCE SUMMARY --
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        (SUM(PROFIT) / NULLIF(SUM(SALES), 0)) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- TOP 10 PRODUCTS BY REVENUE --
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- TOP 10 PRODUCTS BY PROFIT --
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING SUM(SALES) > 0
ORDER BY TOTAL_PROFIT DESC
LIMIT 10;

-- TOP 10 PRODUCTS BY QUANTITY SOLD --
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY TOTAL_UNITS DESC
LIMIT 10;

-- WORST 10 PRODUCTS BY PROFIT --
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY TOTAL_PROFIT ASC
LIMIT 10;

--CATEGORY PERFORMANCE ANALYSIS--
SELECT CATEGORY,
	COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CATEGORY
ORDER BY TOTAL_PROFIT DESC;


SELECT
    PRODUCT,
    SUM(SALES) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
WHERE PRODUCT= 'Laptop'
GROUP BY PRODUCT;


-- TOP 10 PRODUCTS BY REVENUE --
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 1. HIGH REVENUE BUT LOW PROFIT PRODUCTS
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING SUM(SALES) > 5000000
   AND SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_REVENUE DESC;

--HIGH QUANTITY SOLD BUT LOW PROFIT
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING SUM(QUANTITY) > 3300
   AND SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_UNITS DESC;
