--MONTHLY SALES PERFORMANCE
SELECT DATE_TRUNC('MONTH', ORDER_DATE)::DATE AS MONTH,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	SUM(QUANTITY) TOTAL_UNITS,
	ROUND(SUM(SALES), 2) TOTAL_REVENUE,
	ROUND(SUM(PROFIT), 2) TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE)
ORDER BY MONTH;

--QUARTERLY SALES PERFORMANCE --
SELECT
    EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
    EXTRACT(QUARTER FROM ORDER_DATE) AS QUARTER,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY
    EXTRACT(YEAR FROM ORDER_DATE),
    EXTRACT(QUARTER FROM ORDER_DATE)
ORDER BY YEAR, QUARTER;

--SALES PERFORMANCE BY CATEGORY --
SELECT
    CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;

--SALES PERFORMANCE BY STATE --
SELECT
    STATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY STATE
ORDER BY TOTAL_REVENUE DESC;

--TOP 10 CITIES BY REVENUE
SELECT
	CITY,
    STATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CITY, STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--TOP 10 CITIES BY PROFIT
SELECT
	CITY,
    STATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CITY, STATE
ORDER BY TOTAL_PROFIT DESC
LIMIT 10;

--MONTHLY SALES BY CATEGORY
SELECT DATE_TRUNC('MONTH', ORDER_DATE)::DATE AS MONTH, CATEGORY,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE), CATEGORY
ORDER BY MONTH, TOTAL_REVENUE DESC;

--DISCOUNT VS SALES ERFORMANCE
SELECT DISCOUNT,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
	ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DISCOUNT
ORDER BY DISCOUNT;


-- 9. MONTH-OVER-MONTH REVENUE GROWTH --

WITH MONTHLY_SALES AS (
    SELECT
        DATE_TRUNC('month', ORDER_DATE)::DATE AS MONTH,
        SUM(SALES) AS TOTAL_REVENUE
    FROM ECOMMERCE_SALES
    GROUP BY DATE_TRUNC('month', ORDER_DATE)
)

SELECT
    MONTH,
    ROUND(TOTAL_REVENUE, 2) AS TOTAL_REVENUE,
    ROUND(
        LAG(TOTAL_REVENUE) OVER (ORDER BY MONTH),
        2
    ) AS PREVIOUS_MONTH_REVENUE,
    ROUND(
        (
            TOTAL_REVENUE -
            LAG(TOTAL_REVENUE) OVER (ORDER BY MONTH)
        )
        / NULLIF(
            LAG(TOTAL_REVENUE) OVER (ORDER BY MONTH),
            0
        ) * 100,
        2
    ) AS REVENUE_GROWTH_PERCENT
FROM MONTHLY_SALES
ORDER BY MONTH;

-- 10. MONTH-OVER-MONTH PROFIT GROWTH --

WITH MONTHLY_PROFIT AS (
    SELECT
        DATE_TRUNC('month', ORDER_DATE)::DATE AS MONTH,
        SUM(PROFIT) AS TOTAL_PROFIT
    FROM ECOMMERCE_SALES
    GROUP BY DATE_TRUNC('month', ORDER_DATE)
)

SELECT
    MONTH,
    ROUND(TOTAL_PROFIT, 2) AS TOTAL_PROFIT,
    ROUND(
        LAG(TOTAL_PROFIT) OVER (ORDER BY MONTH),
        2
    ) AS PREVIOUS_MONTH_PROFIT,
    ROUND(
        (
            TOTAL_PROFIT -
            LAG(TOTAL_PROFIT) OVER (ORDER BY MONTH)
        )
        / NULLIF(
            LAG(TOTAL_PROFIT) OVER (ORDER BY MONTH),
            0
        ) * 100,
        2
    ) AS PROFIT_GROWTH_PERCENT
FROM MONTHLY_PROFIT
ORDER BY MONTH;
