-- 1. LOSS-MAKING PRODUCTS
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING SUM(PROFIT) < 0
ORDER BY TOTAL_PROFIT ASC;

-- 2. LOSS-MAKING CATEGORIES
SELECT
    CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CATEGORY
HAVING SUM(PROFIT) < 0
ORDER BY TOTAL_PROFIT ASC;

-- 3. HIGH REVENUE BUT LOW PROFIT MARGIN CATEGORIES
SELECT
    CATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CATEGORY
HAVING
    SUM(SALES) > (
        SELECT AVG(CATEGORY_REVENUE)
        FROM (
            SELECT SUM(SALES) AS CATEGORY_REVENUE
            FROM ECOMMERCE_SALES
            GROUP BY CATEGORY
        ) AS X
    )
    AND
    SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_REVENUE DESC;

-- 4. HIGH-REVENUE PRODUCTS WITH LOW PROFIT MARGIN
SELECT
    PRODUCT_ID, PRODUCT, CATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING
    SUM(SALES) > (
        SELECT AVG(PRODUCT_REVENUE)
        FROM (
            SELECT SUM(SALES) AS PRODUCT_REVENUE
            FROM ECOMMERCE_SALES
            GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
        ) AS X
    )
    AND
    SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_REVENUE DESC;

-- 5. HIGH REVENUE BUT LOW PROFIT MARGIN STATES
SELECT
    STATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY STATE
HAVING
    SUM(SALES) > (
        SELECT AVG(STATE_REVENUE)
        FROM (
            SELECT SUM(SALES) AS STATE_REVENUE
            FROM ECOMMERCE_SALES
            GROUP BY STATE
        ) AS X
    )
    AND
    SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_REVENUE DESC;

-- 6. HIGH REVENUE CITIES WITH LOW PROFIT MARGIN
SELECT
    CITY,
    STATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CITY, STATE
HAVING
    SUM(SALES) > (
        SELECT AVG(CITY_REVENUE)
        FROM (
            SELECT SUM(SALES) AS CITY_REVENUE
            FROM ECOMMERCE_SALES
            GROUP BY CITY, STATE
        ) AS X
    )
    AND
    SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_REVENUE DESC;

-- 7. DISCOUNT LEVELS THAT DESTROY PROFIT
SELECT
    DISCOUNT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DISCOUNT
ORDER BY DISCOUNT;

-- 8. MONTHLY PROFIT PERFORMANCE
SELECT
    DATE_TRUNC('MONTH', ORDER_DATE)::DATE AS MONTH,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE)
ORDER BY TOTAL_PROFIT DESC;

-- 9. BEST PRODUCT-CATEGORY COMBINATIONS
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING SUM(PROFIT) > 0
ORDER BY TOTAL_PROFIT DESC
LIMIT 10;

-- 10. HIGH SALES VOLUME BUT WEAK PROFIT
SELECT
    PRODUCT_ID,
    PRODUCT,
    CATEGORY,
    SUM(QUANTITY) AS TOTAL_UNITS,
    ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(
        SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100,
        2
    ) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
HAVING
    SUM(QUANTITY) > 3000
    AND
    SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100 < 10
ORDER BY TOTAL_UNITS DESC;