CREATE TABLE ecommerce_sales (
    order_id VARCHAR(20),
    order_date DATE,
    customer_id VARCHAR(20),
    customer_name VARCHAR(100),
    product_id VARCHAR(20),
    product VARCHAR(100),
    category VARCHAR(100),
    quantity INTEGER,
    sales NUMERIC(12,2),
    discount NUMERIC(5,2),
    profit NUMERIC(12,2),
    city VARCHAR(100),
    state VARCHAR(100),
    payment_mode VARCHAR(50),
    shipping_mode VARCHAR(50)
);

select * from ecommerce_sales

--TOTAL RECORDS--

SELECT COUNT(*) AS TOTAL_RECORDS
FROM ECOMMERCE_SALES

--FIRST 10 RECORDS--
SELECT * FROM ECOMMERCE_SALES LIMIT 10;

--CHECK DATE RANGE--
SELECT
	MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
	MAX(ORDER_DATE) AS LAST_ORDER_DATE
FROM ECOMMERCE_SALES

--COUNT UNIQUE CUSTOMERS-- 
SELECT COUNT(DISTINCT CUSTOMER_ID) TOTAL_CUSTOMERS
FROM ECOMMERCE_SALES;

--COUNT UNIQUE PRODUCTS--
SELECT COUNT(DISTINCT PRODUCT_ID) TOTAL_PRODUCTS
FROM ECOMMERCE_SALES;

--CHECK PRODUCT CATEGORIES--
SELECT DISTINCT CATEGORY FROM ECOMMERCE_SALES
ORDER BY CATEGORY;

--CHECK PAYMENT METHODS--
SELECT DISTINCT PAYMENT_MODE FROM ECOMMERCE_SALES
ORDER BY PAYMENT_MODE;

--CHECK SHIPPING METHODS--
SELECT DISTINCT SHIPPING_MODE FROM ECOMMERCE_SALES
ORDER BY SHIPPING_MODE;

--CHECK MISSING LOCATIONS--
SELECT COUNT(*) UNKNOWN_CITY
FROM ECOMMERCE_SALES
WHERE CITY = 'unknown';

SELECT COUNT(*) UNKNOWN_STATE
FROM ECOMMERCE_SALES
WHERE STATE = 'unknown';

--CHECK NEGATIVE PROFIT--
SELECT COUNT(*) AS LOSS_MAKING_ORDERS
FROM ECOMMERCE_SALES
WHERE PROFIT < 0;

-- CHECK INVALID QUANTITIES--
SELECT COUNT(*) AS INVALID_QUANTITY
FROM ECOMMERCE_SALES
WHERE QUANTITY <=0;

-- CHECK INVALID SALES--
SELECT COUNT(*) AS INVALID_SALES
FROM ECOMMERCE_SALES
WHERE SALES <=0;

--CHECK DISCOUNTS--
SELECT MIN(DISCOUNT) AS MIN_DISCOUNT,
	MAX(DISCOUNT) AS MAX_DISCOUNT
FROM ECOMMERCE_SALES;