SELECT * FROM ECOMMERCE_SALES;

--TOTAL REVENUE--
SELECT ROUND(SUM(SALES),2) AS TOTAL_REVENUE
FROM ECOMMERCE_SALES;

--TOTAL PROFIT--
SELECT ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM ECOMMERCE_SALES;

--TOTAL ORDERS--
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ECOMMERCE_SALES;

--TOTAL CUSTOMERS--
SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM ECOMMERCE_SALES;

--TOTAL QUANTITY SOLD--
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM ECOMMERCE_SALES;

--AVG ORDER VAL--
SELECT ROUND(SUM(SALES)/ COUNT(DISTINCT ORDER_ID), 2) AS AVERAGE_ORDER_VALUE
FROM ECOMMERCE_SALES;

--OVERALL PROFIT MARGIN--
SELECT ROUND((SUM(PROFIT) / SUM(SALES))* 100, 2) AS PROFIT_MARGIN_PERCENTAGE
FROM ECOMMERCE_SALES;


SELECT
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
	COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
	SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
	ROUND(SUM(SALES), 2) AS TOTAL_REVENUE,
	ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
	ROUND(SUM(SALES) / COUNT(DISTINCT ORDER_ID), 2) AS AVERAGE_ORDER_VALUE,
	ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PERCENTAGE
FROM ECOMMERCE_SALES;

--MONTHLY SALES ANALYSIS--
SELECT DATE_TRUNC('MONTH', ORDER_DATE)::DATE AS MONTH,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
	ROUND(SUM(SALES), 2) AS REVENUE,
	ROUND(SUM(PROFIT), 2) AS PROFIT
FROM ECOMMERCE_SALES
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE)
ORDER BY MONTH;

--CATEGORY PERFORMANCE--
SELECT CATEGORY,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
	SUM(QUANTITY) AS UNITS_SOLD,
	ROUND(SUM(SALES), 2) AS REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT,
	ROUND((SUM(PROFIT) / SUM(SALES))* 100, 2) AS PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY CATEGORY
ORDER BY REVENUE DESC;

--TOP 10 PRODUCTS--
SELECT PRODUCT_ID, PRODUCT, CATEGORY,
	SUM(QUANTITY) UNITS_SOLD,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY REVENUE DESC
LIMIT 10;

--TOP 10 BY PROFIT--
SELECT PRODUCT_ID, PRODUCT, CATEGORY,
	SUM(QUANTITY) UNITS_SOLD,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY PROFIT DESC
LIMIT 10;

--WORST 10 PRODUCTS BY PROFIT--
SELECT PRODUCT_ID, PRODUCT, CATEGORY,
	SUM(QUANTITY) UNITS_SOLD,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
GROUP BY PRODUCT_ID, PRODUCT, CATEGORY
ORDER BY PROFIT ASC
LIMIT 10;

--SALES BY STATE--
SELECT STATE,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
WHERE STATE <> 'unknown'
GROUP BY STATE
ORDER BY REVENUE DESC;

--PAYMENT METHOD ANALYSIS--
SELECT PAYMENT_MODE,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
GROUP BY PAYMENT_MODE
ORDER BY REVENUE DESC;

--SHIPPING METHOD ANALYSIS--
SELECT SHIPPING_MODE,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT
FROM ECOMMERCE_SALES
GROUP BY SHIPPING_MODE
ORDER BY REVENUE DESC;


SELECT DISCOUNT,
	COUNT(DISTINCT ORDER_ID) TOTAL_ORDERS,
	ROUND(SUM(SALES), 2) REVENUE,
	ROUND(SUM(PROFIT), 2) PROFIT,
	ROUND(SUM(PROFIT) / SUM(SALES)* 100, 2) PROFIT_MARGIN
FROM ECOMMERCE_SALES
GROUP BY DISCOUNT
ORDER BY DISCOUNT;



SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers,
    SUM(quantity) AS total_quantity_sold,
    ROUND(SUM(sales), 2) AS total_revenue,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value,
    ROUND((SUM(profit) / SUM(sales)) * 100, 2) AS profit_margin_percentage
FROM ecommerce_sales;



